backend:
  name: github
  repo: capriosa/mdwp-phenomic # Gulp will replace this with your GitHub repository
  branch: master # Branch to update (master by default)

public_folder: "content" # the same as your phenomic.source in your package.json
media_folder: "content/assets" # the same as your phenomic.assets in your package.json

collections:
  - name: "post"
    label: "Post"
    folder: "content/posts" # a subfolder of your public_folder
    create: true
    card: {type: "alltype", text: "title"}
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
    meta:
      - {label: "Publish Date", name: "date", widget: "datetime"}